name: Tourism Prediction Pipeline

on:
  workflow_dispatch:
#   push:
#     branches:
#       - main

jobs:
  deploy-webapp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Deploy to HuggingFace Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python src/deployment/hosting.py
