name: Tourism Prediction Pipeline

on:
  workflow_dispatch:
#   push:
#     branches:
#       - main

jobs:
  model-training:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Model Building
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/src/models
          python src/models/train.py
