name: Tourism Prediction Pipeline

on:
  workflow_dispatch:
#   push:
#     branches:
#       - main

jobs:
  data-prep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run Data Preparation
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/src/data
          python src/data/prepare.py
